"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fibonacci(limit):
    start_array = [0, 1]
    while start_array[-1] < limit:
        start_array.append(start_array[-1] + start_array[-2])
    return start_array[:-1]


def main(limit):
    sequence = fibonacci(limit)
    even_sequence = [numbers for numbers in sequence if numbers % 2 == 0]
    print(even_sequence)
    return sum(even_sequence)


if __name__ == "__main__":
    print(main(4000000))
